# Generated by Django 4.1.1 on 2022-09-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgmUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tgm_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserVacancyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('salary', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hh_main.tgmuser')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='hh_main.uservacancystatus')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('user', models.ManyToManyField(to='hh_main.tgmuser')),
            ],
        ),
        migrations.AddField(
            model_name='uservacancystatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uv_user', to='hh_main.vacancy'),
        ),
        migrations.AddField(
            model_name='uservacancystatus',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uv_vacancy', to='hh_main.vacancy'),
        ),
        migrations.CreateModel(
            name='UserVacancyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_auto_score', models.IntegerField()),
                ('second_auto_score', models.IntegerField()),
                ('user_score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_user', to='hh_main.vacancy')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_vacancy', to='hh_main.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='UserStopWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10000)),
                ('user', models.ManyToManyField(to='hh_main.tgmuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserGoodWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10000)),
                ('user', models.ManyToManyField(to='hh_main.tgmuser')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=1000)),
                ('user', models.ManyToManyField(to='hh_main.tgmuser')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_main.vacancy')),
            ],
        ),
    ]
