# Generated by Django 4.1.1 on 2022-09-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
