# Generated by Django 4.1.1 on 2022-09-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_main', '0002_alter_tgmuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmuser',
            name='tgm_id',
            field=models.IntegerField(unique=True),
        ),
    ]
